### ISSUE TITLE
doesn't build with OpenMPI 5 due to removed symbols

### ISSUE THREAD

**Issue by BenWibking** [pmodels/pilgrim#26]
For MPI implementations that have removed symbols that have now been removed from the MPI standard, pilgrim doesn't compile:

```
$ make
  CC       src/decoder/pilgrim_app_generator-pilgrim_app_generator.o
In file included from ./include/pilgrim_logger.h:9,
                 from ./include/pilgrim.h:11,
                 from src/decoder/pilgrim_app_generator.c:11:
/projects/cvz/bwibking/ompi5_main_20230209/include/mpi.h:349:63: error: expected '}' before ';' token
  349 | #define THIS_SYMBOL_WAS_REMOVED_IN_MPI30(symbol, new_symbol) 0; _Static_assert(0, #symbol " was removed in MPI-3.0.  Use " #new_symbol " instead.")
      |                                                               ^
/projects/cvz/bwibking/ompi5_main_20230209/include/mpi.h:1213:24: note: in expansion of macro 'THIS_SYMBOL_WAS_REMOVED_IN_MPI30'
 1213 | #        define MPI_LB THIS_SYMBOL_WAS_REMOVED_IN_MPI30(MPI_LB, MPI_Type_create_resized);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/pilgrim_consts.h:51:5: note: in expansion of macro 'MPI_LB'
   51 |     MPI_LB,
      |     ^~~~~~
In file included from src/decoder/pilgrim_app_generator.c:13:
./include/pilgrim_consts.h:34:40: note: to match this '{'
   34 | MPI_Datatype builtin_mpi_datatypes[] = {
      |                                        ^
make: *** [Makefile:954: src/decoder/pilgrim_app_generator-pilgrim_app_generator.o] Error 1
```

**Comment by wangvsa** [comment]
Thanks for pointing this out, turns out it also have a few issues with older versions of openmpi as well. I have fixed those and it should work for openmpi 3 and 4. Will take a look at Openmpi 5 now.

**Comment by khatharsis42** [comment]
It seems like this issue is still here, even for the OpenMPI 4.1.5.

**Comment by wangvsa** [comment]
Solved in the new [PR](https://github.com/pmodels/pilgrim/pull/30).
The PR checks MPI version and ignores those two deprecated datatypes for version 3 and above.
